name: deploy
on: push
# on:
#   push:
#     branches:
#       # - master
#       - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      html: ${{ steps.html.outputs.test }}
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
      KODEVOPS_BLOG_DEPLOY_KEY: ${{ secrets.KODEVOPS_BLOG_DEPLOY_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # https://github.com/ruby/setup-ruby
          ruby-version: 2.7
      - name: Install dependencies
        run: bundle install
      - name: Build jekyll
        id: html
        run: bash ./script/cibuild
      - name: Test
        run: pwd && ls -al && ls -al ~/.ssh
      - name: Test
        run: -|
          echo "$KODEVOPS_BLOG_DEPLOY_KEY" > ~/.ssh/id_rsa
          && chmod 600 > ~/.ssh/id_rsa
          && git clone git@github.com:kodevops/kodevops.github.io.git
          ls -al
