name: deploy
on: push
# on:
#   push:
#     branches:
#       # - master
#       - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      html: ${{ steps.html.outputs.test }}
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # https://github.com/ruby/setup-ruby
          ruby-version: 2.7
      - name: Install dependencies
        run: bundle install
      - name: Build jekyll
        id: html
        run: bash ./script/cibuild
      - name: Test
        run: pwd && ls -al
      - uses: actions/checkout@v2
        with:
          repository: git@github.com:kodevops/kodevops.github.io.git
          ssh-key: ${{ secrets.KODEVOPS_BLOG_DEPLOY_KEY }}
          path: kodevops.github.io.git
      - name: Commit & Push
        run: pwd && ls -al
